/////////////////////////////////////////////////////////////
//          Copyright Vadym Senkiv 2025.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          https://www.boost.org/LICENSE_1_0.txt)
/////////////////////////////////////////////////////////////

#pragma once

// NOTE: file is generated by CMake

namespace elib::version
{
  constexpr const char* str()
  {
    return "1.9.0";
  }

  constexpr unsigned major()
  {
    return 1;
  }

  constexpr unsigned minor()
  {
    return 9 +0;
  }

  constexpr unsigned patch()
  {
    return 0 +0;
  }

  constexpr unsigned tweak()
  {
    return  +0;
  }
}
